spring:
  application:
    name: converter-service
  cloud:
    stream:
      bindings:
        input:
          destination: images.preview.queue
images:
  url-provider:
    type: static # supported values: static, self  
    base-url: http://localhost:7071
