version: '3.3'

services:
  rabbitmq:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3.7.8-management-alpine
    volumes:
        - ./rabbitmq:/var/lib/rabbitmq
    ports:
        - '15672:15672'
        - '5672:5672'
  mongodb:
    container_name: mongo
    hostname: mongo
    image: bitnami/mongodb
    volumes:
        - ./mongodb:/bitnami
    ports:
        - '27017:27017'
