spring:
  application:
    name: converter-service
  cloud:
    stream:
      bindings:
        input:
          destination: images.preview.queue
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
      
logging:
  file: converter-service.log
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
    file:    "%d %-5level [%thread] %logger : %msg%n"    
  level:
    console: 'INFO'
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR
    ws.slink.test: INFO

images:
  datastore:
    fs: 
      path:
        upload:  "/Users/kami/work/dev/portfolio/tasks/image-upload-service/upload/images/"
        preview: "/Users/kami/work/dev/portfolio/tasks/image-upload-service/upload/preview"
      

