spring:
  application:
    name: upload-service
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
server:
  port: 7070
  hostname: 0.0.0.0
  
logging:
  file: upload-service.log
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
    file:    "%d %-5level [%thread] %logger : %msg%n"    
  level:
    console: 'INFO'
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    ws.slink.test: INFO

  