spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 7070

logging:
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
    file:    "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    ws.slink.test: ERROR

images:
  datastore:
    type: fs
    fs:
      path:
        upload:  "/upload/images"
        preview: "/upload/preview"
